title: KBNL dataservices documentation STAGING
basetitle: "KB Dataservices"

description: "Public documentation, code, insights, tips & tricks about the public datasets and collections of the KB, national library of the Netherlands."
basedescription: "dataservices of the KB, the national library of the Netherlands"

url: "https://kbnldataservices.github.io"
baseurl: "/public-docs-staging"


email: dataservices@kb.nl
twitter_username: KBdataservices
github_username:  KBNLdataservices


#theme: theme-red
#remote_theme: rundocs/jekyll-rtd-theme
#github: [metadata]

repository: kbnldataservices/public-docs-staging

topnavlogo: "/assets/images/logo-kb-zwart-transparant.png"


#debug:
#   compress: true
  #- dist: false #enables use of local /assets/js/theme.js
#   shortcodes: true

encoding: UTF-8

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
  - contact
  - copyright
  - dataservices
  - kbga
  - restrictedsets
  - updates.md
  - opensets/bibliotheekinzicht
  - opensets/dbnl
  - opensets/bookbindings.md
  - opensets/brinkman.md
  - opensets/corp-thes.md
  - opensets/digger.md
  - opensets/entangled-histories.md
  - opensets/europeana-newspapers-ner.md
  - opensets/example-set.md
  - opensets/ggt.md
  - opensets/ground-truth-impact .md
  - opensets/kbcode.md
  - opensets/kbnl-websitetexts.md
  - opensets/maps-atlasses.md
  - opensets/nbt.md
  - opensets/newspaper-ngram.md
  - opensets/nta.md
  - opensets/picturebooks.md
  - opensets/stcn.md
  - opensets/web-collection-chinese-netherlands.md
  - opensets/web-collection-internet-archaeology.md

