title: KBNL dataservices documentation STAGING
email: dataservices@kb.nl
twitter_username: KBdataservices
github_username:  KBNLdataservices

url: "https://kbnldataservices.github.io"
baseurl: "/public-docs-staging"

#theme: null
#remote_theme: rundocs/jekyll-rtd-theme
#github: metadata

repository: kbnldataservices/public-docs-staging

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

encoding: UTF-8

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-github-metadata

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
  - contact
  - copyright
  - dataservices
  - kbga
  - restrictedsets
  - updates.md
  - opensets/bibliotheekinzicht
  - opensets/dbnl
  - opensets/bookbindings.md
  - opensets/brinkman.md
  - opensets/corp-thes.md
  - opensets/digger.md
  - opensets/entangled-histories.md
  - opensets/europeana-newspapers-ner.md
  - opensets/example-set.md
  - opensets/ggt.md
  - opensets/ground-truth-impact .md
  - opensets/kbcode.md
  - opensets/kbnl-websitetexts.md
  - opensets/maps-atlasses.md
  - opensets/nbt.md
  - opensets/newspaper-ngram.md
  - opensets/nta.md
  - opensets/picturebooks.md
  - opensets/stcn.md
  - opensets/web-collection-chinese-netherlands.md
  - opensets/web-collection-internet-archaeology.md
